{{- if .Values.config.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "complex-test-chart.fullname" . }}-config
  labels:
    {{- include "complex-test-chart.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
